sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t techflookup/far-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run techflookup/far-react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t techflookup/far-client ./client
  - docker build -t techflookup/far-nginx ./nginx
  - docker build --build-arg JWT=$FAR_JWT_PRIVATEKEY --build-arg MAIL=$FAR_MAIL_PASSWORD --build-arg DB=$FAR_DB_PASSWORD -t techflookup/far-auth ./auth
  - docker build --build-arg JWT=$FAR_JWT_PRIVATEKEY --build-arg MAIL=$FAR_MAIL_PASSWORD --build-arg DB=$FAR_DB_PASSWORD --build-arg ACCESS=$AWS_ACCESS_KEY --build-arg SECRET=$AWS_SECRET_KEY -t techflookup/far-api ./api

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push techflookup/far-client
  - docker push techflookup/far-nginx
  - docker push techflookup/far-auth
  - docker push techflookup/far-api

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: docker-far
  env: DockerFar-env
  bucket_name: elasticbeanstalk-ap-south-1-837962867465
  bucket_path: docker-far
  on:
    branch: master
  access_key_id: $AWS_EBS_ACCESS_KEY_ID
  secret_access_key: $AWS_EBS_ACCESS_SECRET_KEY
