version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  auth:
    build:
      dockerfile: Dockerfile.dev
      context: ./auth
    volumes:
      - /usr/app/node_modules
      - ./auth:/usr/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /usr/app/node_modules
      - ./api:/usr/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
